# Generated by Django 4.2.23 on 2025-07-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("stock", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="inventoryitem", name="quantity"),
        migrations.AddField(
            model_name="inventoryitem",
            name="current_stock_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="initial_stock_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="is_sold_in_kgs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="retail_price_per_unit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="unit_of_measure",
            field=models.CharField(
                choices=[("KG", "Kilogram"), ("PIECE", "Piece")],
                default="KG",
                max_length=50,
            ),
        ),
    ]
