# Generated by Django 4.2.23 on 2025-07-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("stock", "0002_remove_inventoryitem_quantity_and_more")]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem", name="initial_stock_quantity"
        )
    ]
