# Generated by Django 4.2.23 on 2025-07-29 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("stock", "0003_remove_inventoryitem_initial_stock_quantity")]

    operations = [
        migrations.RenameField(
            model_name="inventoryitem",
            old_name="current_stock_quantity",
            new_name="stock_quantity",
        )
    ]
