# Generated by Django 4.2.23 on 2025-07-30 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_rename_current_stock_quantity_inventoryitem_stock_quantity")
    ]

    operations = [
        migrations.RenameField(
            model_name="inventoryitem",
            old_name="stock_quantity",
            new_name="total_stock_quantity",
        ),
        migrations.RemoveField(model_name="inventoryitem", name="expiry_date"),
        migrations.RemoveField(
            model_name="inventoryitem", name="retail_price_per_unit"
        ),
        migrations.RemoveField(model_name="inventoryitem", name="supplier"),
        migrations.RemoveField(model_name="inventoryitem", name="unit_price"),
        migrations.CreateModel(
            name="InventoryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "retail_price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="stock.inventoryitem",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stock.supplier",
                    ),
                ),
            ],
        ),
    ]
