# Generated by Django 4.2.23 on 2025-07-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stock",
            "0005_rename_stock_quantity_inventoryitem_total_stock_quantity_and_more",
        )
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="sale_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        )
    ]
