# Generated by Django 4.2.23 on 2025-07-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("stock", "0006_inventoryitem_sale_price")]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="last_system_sale_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        )
    ]
