# Generated by Django 4.2.23 on 2025-08-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("stock", "0007_inventoryitem_last_system_sale_price")]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="total_stock_quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        )
    ]
