# Generated by Django 4.2.23 on 2025-08-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("billing", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("online", "Online")],
                default="cash",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="rent_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bill",
            name="rent_payer",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("company", "Company"),
                    ("shared", "Shared"),
                ],
                default="customer",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="cnic",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
