# Generated by Django 4.2.23 on 2025-08-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billing",
            "0002_bill_payment_method_bill_rent_amount_bill_rent_payer_and_more",
        )
    ]

    operations = [
        migrations.AddField(
            model_name="billitem",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="billitem",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("none", "No Discount"),
                    ("fixed", "Fixed Amount"),
                    ("percentage", "Percentage (%)"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
