# Generated by Django 4.2.23 on 2025-08-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("billing", "0003_billitem_discount_amount_billitem_discount_type")]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("none", "No Discount"),
                    ("fixed", "Fixed Amount"),
                    ("percentage", "Percentage (%)"),
                ],
                default="none",
                max_length=10,
            ),
        )
    ]
