# Generated by Django 4.2.23 on 2025-08-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("billing", "0004_bill_discount_type")]

    operations = [
        migrations.RemoveField(model_name="bill", name="discount"),
        migrations.RemoveField(model_name="bill", name="discount_type"),
    ]
