# Generated by Django 4.2.23 on 2025-08-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("billing", "0005_remove_bill_discount_remove_bill_discount_type")]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="bill_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        )
    ]
