# Generated by Django 4.2.23 on 2025-08-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("billing", "0006_bill_bill_number")]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")],
                default="open",
                max_length=10,
            ),
        )
    ]
