# Generated by Django 4.2.23 on 2025-08-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("billing", "0007_bill_status")]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="online_amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="bill",
            name="rent_company_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bill",
            name="rent_customer_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="bill",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("online", "Online"), ("both", "Both")],
                default="cash",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="rent_payer",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("company", "Company"),
                    ("shared", "Shared"),
                    ("both", "Both"),
                ],
                default="customer",
                max_length=10,
            ),
        ),
    ]
