# Generated by Django 4.2.23 on 2025-08-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_bill_online_amount_paid_bill_rent_company_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('advance', 'Advance')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
