# Generated by Django 4.2.23 on 2025-08-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_bill_status_alter_billitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('advance', 'Advance'), ('paid_later', 'Paid Later')], default='open', max_length=10),
        ),
    ]
