# Generated by Django 4.2.23 on 2025-08-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='reason',
            field=models.CharField(default='not used', max_length=255),
        ),
    ]
