# Generated by Django 4.2.23 on 2025-09-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_return_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
