# Generated by Django 4.2.23 on 2025-09-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("billing", "0012_bill_closed_at")]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("advance", "Advance"),
                    ("paid_later", "Paid Later"),
                    ("shipped_pending", "Shipped/Charges Pending"),
                ],
                default="open",
                max_length=20,
            ),
        )
    ]
