# Generated by Django 4.2.23 on 2025-09-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("billing", "0013_alter_bill_status")]

    operations = [
        migrations.AddField(
            model_name="return",
            name="amount_returned",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="return",
            name="quantity_returned",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
