# Generated by Django 4.2.23 on 2025-09-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("billing", "0014_return_amount_returned_and_more")]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="remaining_charges",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        )
    ]
