# Generated by Django 4.2.23 on 2025-08-26 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeadvance',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='date_given',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
