# Generated by Django 5.2.4 on 2025-07-28 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentCategory",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="inventory.parentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent Category",
                "verbose_name_plural": "Parent Categories",
                "db_table": "ParentCategories",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("sku_number", models.CharField(max_length=100, unique=True)),
                ("item_name", models.CharField(max_length=255)),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[("KG", "Kilogram"), ("PIECE", "Piece")], max_length=10
                    ),
                ),
                ("sold_in_kgs", models.BooleanField(default=True)),
                (
                    "retail_price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "current_stock_quantity",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.parentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "db_table": "Items",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("movement_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("IN_OPENING", "In - Opening Stock"),
                            ("IN_PURCHASE", "In - Purchase"),
                            ("OUT_SALE", "Out - Sale"),
                            ("OUT_ADJUSTMENT", "Out - Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity_changed",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                ("movement_date", models.DateTimeField(auto_now_add=True)),
                (
                    "reference_document",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.item"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Movement",
                "verbose_name_plural": "Stock Movements",
                "db_table": "StockMovements",
            },
        ),
    ]
