# Generated by Django 4.2.23 on 2025-09-18 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("stock", "0008_alter_inventoryitem_total_stock_quantity")]

    operations = [
        migrations.CreateModel(
            name="DailySaleSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "total_sale_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("average_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.inventorycategory",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Daily Sale Summaries",
                "unique_together": {("date", "sku")},
            },
        )
    ]
