# Generated by Django 4.2.23 on 2025-07-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wallet", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="walletentry", options={"ordering": ["-transaction_date"]}
        ),
        migrations.RemoveField(model_name="walletentry", name="platform"),
        migrations.AddField(
            model_name="walletentry",
            name="balance_after_transaction",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="walletentry",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="walletentry",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("return", "Return"),
                    ("salary", "Employee Salary"),
                    ("expense", "Other Expense"),
                    ("deposit", "Deposit"),
                ],
                default="sale",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="walletentry",
            name="transaction_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
