# Generated by Django 4.2.23 on 2025-08-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_alter_walletentry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletentry',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('return', 'Return'), ('salary', 'Employee Salary'), ('expense', 'Other Expense'), ('deposit', 'Deposit'), ('advance_salary', 'Advance Salary'), ('other', 'Other Transaction')], default='sale', max_length=20),
        ),
    ]
