# Generated by Django 4.2.23 on 2025-09-18 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0015_bill_remaining_charges"),
        ("wallet", "0003_alter_walletentry_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="walletentry",
            name="bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.bill",
            ),
        )
    ]
