# Generated by Django 4.2.23 on 2025-09-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wallet", "0004_walletentry_bill")]

    operations = [
        migrations.CreateModel(
            name="DailyWalletSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "start_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "end_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={"ordering": ["-date"]},
        )
    ]
