# Generated by Django 4.2.23 on 2025-09-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wallet", "0005_dailywalletsummary")]

    operations = [
        migrations.AddField(
            model_name="dailywalletsummary",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
