# Generated by Django 4.2.23 on 2025-09-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wallet", "0006_dailywalletsummary_start_time")]

    operations = [
        migrations.AddField(
            model_name="walletentry",
            name="payment_mode",
            field=models.CharField(
                choices=[("cash", "Cash"), ("online", "Online"), ("both", "Both")],
                default="cash",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="walletentry",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("return", "Return"),
                    ("salary", "Employee Salary"),
                    ("expense", "Other Expense"),
                    ("deposit", "Deposit"),
                    ("advance_salary", "Advance Salary"),
                    ("rent", "MSI Rent"),
                    ("other", "Other Transaction"),
                ],
                default="sale",
                max_length=20,
            ),
        ),
    ]
