# Generated by Django 4.2.23 on 2025-09-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wallet", "0007_walletentry_payment_mode_and_more")]

    operations = [
        migrations.AddField(
            model_name="walletentry",
            name="cash_received",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="walletentry",
            name="online_received",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
